"""Generate Docker configuration."""
from pathlib import Path


def generate_docker_layer(config: dict, project_path: Path):
    if not config["include_docker"]:
        return

    services = {
        "chroma": '''
  chroma:
    image: chromadb/chroma:latest
    ports:
      - "8001:8000"
    volumes:
      - chroma_data:/chroma/chroma''',
        "qdrant": '''
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage''',
        "weaviate": '''
  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - "8080:8080"
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
    volumes:
      - weaviate_data:/var/lib/weaviate''',
        "pgvector": '''
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: agent
      POSTGRES_PASSWORD: agent
      POSTGRES_DB: vectors
    volumes:
      - pg_data:/var/lib/postgresql/data''',
    }

    volumes = {
        "chroma": "  chroma_data:",
        "qdrant": "  qdrant_data:",
        "weaviate": "  weaviate_data:",
        "pgvector": "  pg_data:",
    }

    vdb = config["vector_db"]
    svc = services.get(vdb, "")
    vol = volumes.get(vdb, "")

    compose = f'''# Docker Compose for {config['project_name']}
# Generated by LaunchpadAI

services:
  agent:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    depends_on:{f"""
      - {vdb if vdb != 'pgvector' else 'postgres'}""" if svc else ""}
      []
{svc}

volumes:
{vol if vol else "  {}"}
'''

    _write(project_path / "docker-compose.yml", compose)

    # Dockerfile
    dockerfile = f'''FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "api.routes:app", "--host", "0.0.0.0", "--port", "8000"]
'''
    _write(project_path / "Dockerfile", dockerfile)


def _write(path: Path, content: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as f:
        f.write(content)
