"""Integration tests — cross-generator consistency checks.

These tests verify that files generated by different generators
are compatible with each other (e.g., imports match actual files).
"""
import ast
import pytest
from launchpadai.generators.project import ProjectGenerator


AGENT_FILES = {
    "plain": "base.py",
    "langchain": "graph.py",
    "llamaindex": "agent.py",
    "crewai": "crew.py",
    "haystack": "base.py",
}


@pytest.mark.integration
@pytest.mark.parametrize("framework", ["plain", "langchain", "llamaindex", "crewai"])
def test_api_layer_imports_match_agent_files(tmp_path, make_config, framework):
    """api_layer.py should import from the correct agent module."""
    config = make_config(framework=framework)
    project_path = tmp_path / f"api-{framework}"
    project_path.mkdir()
    ProjectGenerator(config, project_path).generate()

    api_content = (project_path / "api" / "routes.py").read_text()
    agent_file = AGENT_FILES[framework]

    # The agent file referenced in the import must exist
    assert (project_path / "agents" / agent_file).exists(), \
        f"api imports agent module but agents/{agent_file} missing"


@pytest.mark.integration
@pytest.mark.parametrize("framework", ["plain", "langchain", "llamaindex", "crewai"])
def test_eval_layer_import_consistency(tmp_path, make_config, framework):
    """eval_layer always imports agents.base — verify the file exists.

    KNOWN BUG: eval_layer hardcodes 'from agents.base import agent'
    but LangChain generates agents/graph.py, not agents/base.py.
    This test documents the bug.
    """
    config = make_config(framework=framework, include_eval=True)
    project_path = tmp_path / f"eval-{framework}"
    project_path.mkdir()
    ProjectGenerator(config, project_path).generate()

    eval_content = (project_path / "eval" / "run_eval.py").read_text()

    if "from agents.base import agent" in eval_content:
        # This import requires agents/base.py to exist
        if framework != "plain" and framework != "haystack":
            pytest.xfail(
                f"KNOWN BUG: eval_layer imports agents.base but "
                f"{framework} generates agents/{AGENT_FILES[framework]}"
            )


@pytest.mark.integration
@pytest.mark.parametrize("framework", ["plain", "langchain", "llamaindex", "crewai"])
def test_cli_runner_import_consistency(tmp_path, make_config, framework):
    """cli_runner always imports agents.base — verify compatibility.

    KNOWN BUG: Same issue as eval_layer.
    """
    config = make_config(framework=framework)
    project_path = tmp_path / f"cli-{framework}"
    project_path.mkdir()
    ProjectGenerator(config, project_path).generate()

    cli_content = (project_path / "agents" / "cli_runner.py").read_text()

    if "from agents.base import agent" in cli_content:
        if framework != "plain" and framework != "haystack":
            pytest.xfail(
                f"KNOWN BUG: cli_runner imports agents.base but "
                f"{framework} generates agents/{AGENT_FILES[framework]}"
            )


@pytest.mark.integration
@pytest.mark.parametrize("framework", ["langchain", "llamaindex", "crewai"])
@pytest.mark.parametrize("ui", ["streamlit", "gradio"])
def test_ui_layer_import_consistency(tmp_path, make_config, framework, ui):
    """UI layers import agents.base — verify compatibility.

    KNOWN BUG: Same issue as eval_layer.
    """
    config = make_config(framework=framework, ui=ui)
    project_path = tmp_path / f"ui-{framework}-{ui}"
    project_path.mkdir()
    ProjectGenerator(config, project_path).generate()

    ui_content = (project_path / "ui" / "app.py").read_text()

    if "from agents.base import agent" in ui_content:
        pytest.xfail(
            f"KNOWN BUG: {ui} UI imports agents.base but "
            f"{framework} generates agents/{AGENT_FILES[framework]}"
        )


@pytest.mark.integration
def test_ml_predict_tool_generated_with_ml_pipeline(tmp_path, make_config):
    """ml_pipeline should generate tools/ml_predict.py that references tools/registry."""
    config = make_config(include_ml_pipeline=True)
    project_path = tmp_path / "ml-tools"
    project_path.mkdir()
    ProjectGenerator(config, project_path).generate()

    assert (tmp_path / "ml-tools" / "tools" / "ml_predict.py").exists()
    assert (tmp_path / "ml-tools" / "tools" / "registry.py").exists()
