"""The framework adapter contract."""
from pathlib import Path
from typing import Callable

from pydantic import BaseModel, ConfigDict


class FrameworkAdapter(BaseModel):
    """Frozen description of one orchestration framework integration.

    The adapter owns everything framework-specific about a generated project:
    the orchestration files inside agents/ and the agents/__init__.py
    entrypoint. Shared layers (guardrails, memory, tools, API, eval, UI, ...)
    are framework-agnostic and generated by core.
    """

    model_config = ConfigDict(frozen=True)

    name: str
    display_name: str
    tier: int  # 1 = fully supported and tested; 2 = maintained adapter, reduced surface
    description: str
    orchestrations: tuple[str, ...]  # subset of {"single", "sequential", "supervisor"}
    generate: Callable[..., None]  # (config: ProjectConfig, project_path: Path) -> None
    # True when the adapter's orchestration calls models/llm/provider.py directly,
    # so the generated mock LLM provider (LLM_MOCK=1) can drive the full agent loop
    # offline. Frameworks that construct their own LLM clients (LangGraph, CrewAI)
    # get entrypoint-level tests instead.
    uses_llm_provider: bool = False


def write(path: Path, content: str):
    """Write a generated file, creating parent directories."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as f:
        f.write(content)
